#!/usr/bin/env python3
"""Sample kit converter (M7: one RAM-resident kit linked into the ROM).

WAV -> mono 8-bit signed PCM at PCM_RATE, silence-trimmed, per-slot and
total budget capped. Emits a ca65 source with the sample bytes (RODATA)
and an 8-slot directory (ptr, len) exported as _kit_dir for C.

Usage: alynxdj_sample.py <kitdir> <out.s>
"""
import os
import sys
import wave

import numpy as np

PCM_RATE = 7812.5           # timer7 @ 1us, BKUP=127
SLOT_CAP = 2600             # bytes per slot
KIT_CAP = 11400             # total budget (RAM-resident, see DESIGN §13)
TRIM_DB = -48.0             # trailing-silence threshold


def load(path):
    w = wave.open(path)
    n, ch, sw, fr = (w.getnframes(), w.getnchannels(),
                     w.getsampwidth(), w.getframerate())
    raw = w.readframes(n)
    if sw == 2:
        d = np.frombuffer(raw, np.int16).astype(np.float32) / 32768.0
    else:
        d = (np.frombuffer(raw, np.uint8).astype(np.float32) - 128) / 128.0
    if ch > 1:
        d = d.reshape(-1, ch).mean(axis=1)
    # resample (linear)
    t = np.arange(int(len(d) * PCM_RATE / fr)) * (fr / PCM_RATE)
    d = np.interp(t, np.arange(len(d)), d)
    # trim trailing silence
    thresh = 10 ** (TRIM_DB / 20)
    env = np.abs(d)
    keep = np.where(env > thresh)[0]
    if len(keep):
        d = d[: min(keep[-1] + int(0.01 * PCM_RATE), len(d))]
    d = d[:SLOT_CAP]
    peak = np.abs(d).max() or 1.0
    return np.clip(np.round(d / peak * 120), -127, 127).astype(np.int8)


def main(kitdir, out):
    wavs = sorted(f for f in os.listdir(kitdir) if f.lower().endswith(".wav"))[:8]
    slots = [load(os.path.join(kitdir, f)) for f in wavs]
    total = sum(len(s) for s in slots)
    if total > KIT_CAP:
        # shave the longest slots until the kit fits
        while total > KIT_CAP:
            i = max(range(len(slots)), key=lambda k: len(slots[k]))
            slots[i] = slots[i][: len(slots[i]) - 256]
            total = sum(len(s) for s in slots)
    with open(out, "w") as f:
        f.write("; Generated by tools/alynxdj_sample.py from %s - do not edit.\n"
                % kitdir)
        f.write("        .export _kit_dir\n        .rodata\n")
        for i, s in enumerate(slots):
            f.write("kit_s%d:\n" % i)
            for o in range(0, len(s), 16):
                f.write("        .byte "
                        + ",".join(str(int(b) & 0xFF) for b in s[o:o+16])
                        + "\n")
        f.write("_kit_dir:\n")
        for i, s in enumerate(slots):
            f.write("        .word kit_s%d, %d\n" % (i, len(s)))
    print("kit: %d slots, %d bytes (%s)"
          % (len(slots), total, ", ".join("%d" % len(s) for s in slots)))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
