#!/usr/bin/env python3
"""Note table generator.

For each note C-1..B-8 (note byte 1..96; 0 = empty) pick the Mikey channel
timer (clocksel 0..6 = 1<<n microseconds, 8-bit BACKUP) that lands nearest
the equal-tempered pitch: square f = 1 / (2 * (BACKUP+1) * clock).
Finer clocks give better resolution, so take the smallest clocksel whose
BACKUP fits in 8 bits.

Emits build/notes.h: note_clock[], note_bkup[], note names, plus worst-case
cents error as a comment (regenerate and eyeball after any range change).
"""
import math
import sys

A4 = 440.0
NAMES = ["C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"]


def freq(n):            # n: 0 = C-1 ... MIDI-style semitone index from C1
    # C1 = MIDI 24 = 32.703 Hz; A4 = MIDI 69
    return A4 * 2.0 ** ((n + 24 - 69) / 12.0)


def best(f):
    cands = []
    for clocksel in range(7):
        clock = (1 << clocksel) * 1e-6
        b = round(1.0 / (2.0 * f * clock)) - 1
        if 0 <= b <= 255:
            actual = 1.0 / (2.0 * (b + 1) * clock)
            cents = 1200.0 * math.log2(actual / f)
            cands.append((abs(cents), clocksel, b, actual, cents))
    cands.sort()
    return cands[0]


def main(out):
    # 96 playable notes + 43 extension entries: the WAV triangle divider is
    # 24 per cycle (vs the square's 2), so its lookup is note+43 semitones
    # (12.01x) — the extension keeps that in-table for the whole top range.
    NEXT = 96 + 43
    rows = []
    worst = (0.0, "")
    for i in range(NEXT):
        f = freq(i)
        acents, clocksel, b, actual, cents = best(f)
        name = NAMES[i % 12] + str(i // 12 + 1)
        rows.append((name, clocksel, b, f, actual, cents))
        if acents > worst[0] and i < 96:
            worst = (acents, name)
    with open(out, "w") as fo:
        fo.write("/* Generated by tools/maketables.py - do not edit.\n")
        fo.write(" * note byte 1..96 = C-1..B-8 (0 = empty); index tables with note-1.\n")
        fo.write(" * entries 96..138 extend the range for the WAV triangle (+43).\n")
        fo.write(" * worst playable-range error: %.2f cents at %s */\n" % worst)
        fo.write("#define NOTE_MIN 1\n#define NOTE_MAX 96\n")
        fo.write("static const unsigned char note_clock[%d] = {\n" % NEXT)
        for i in range(0, NEXT, 12):
            fo.write("    " + ",".join("%d" % r[1] for r in rows[i:i+12]) + ",\n")
        fo.write("};\n")
        fo.write("static const unsigned char note_bkup[%d] = {\n" % NEXT)
        for i in range(0, NEXT, 12):
            fo.write("    " + ",".join("%3d" % r[2] for r in rows[i:i+12]) + ",\n")
        fo.write("};\n")
        fo.write("/* name table: 2 chars + octave digit, for the editor */\n")
        fo.write('static const char note_names[96][3] = {\n')
        for i in range(0, 96, 12):
            fo.write("    " + ",".join('"%s"' % r[0] for r in rows[i:i+12]) + ",\n")
        fo.write("};\n")
    err = max(abs(r[5]) for r in rows)
    print("notes.h: 96 notes, worst error %.2f cents (%s)" % worst)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "build/notes.h")
