#!/usr/bin/env python3
"""Note table generator.

For each note C-1..B-8 (note byte 1..96; 0 = empty) pick the Mikey channel
timer (clocksel 0..6 = 1<<n microseconds, 8-bit BACKUP) that lands nearest
the equal-tempered pitch: square f = 1 / (2 * (BACKUP+1) * clock).
Finer clocks give better resolution, so take the smallest clocksel whose
BACKUP fits in 8 bits.

Emits build/notes.h: note_clock[], note_bkup[], note names, plus worst-case
cents error as a comment (regenerate and eyeball after any range change).
"""
import math
import sys

A4 = 440.0
NAMES = ["C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"]
MAX_WAVE_IRQ = 6250.0       # real-hardware dual-DAC budget (WAV + KIT)


def freq(n):            # n: 0 = C-1 ... MIDI-style semitone index from C1
    # C1 = MIDI 24 = 32.703 Hz; A4 = MIDI 69
    return A4 * 2.0 ** ((n + 24 - 69) / 12.0)


def best(f):
    cands = []
    for clocksel in range(7):
        clock = (1 << clocksel) * 1e-6
        b = round(1.0 / (2.0 * f * clock)) - 1
        if 0 <= b <= 255:
            actual = 1.0 / (2.0 * (b + 1) * clock)
            cents = 1200.0 * math.log2(actual / f)
            cands.append((abs(cents), clocksel, b, actual, cents))
    cands.sort()
    return cands[0]


def main(out):
    # 96 playable notes + 43 extension entries: the WAV triangle divider is
    # 24 per cycle (vs the square's 2), so its lookup is note+43 semitones
    # (12.01x) — the extension keeps that in-table for the whole top range.
    NEXT = 96 + 43
    rows = []
    worst = (0.0, "")
    for i in range(NEXT):
        f = freq(i)
        acents, clocksel, b, actual, cents = best(f)
        name = NAMES[i % 12] + str(i // 12 + 1)
        rows.append((name, clocksel, b, f, actual, cents))
        if acents > worst[0] and i < 96:
            worst = (acents, name)
    with open(out, "w") as fo:
        fo.write("/* Generated by tools/maketables.py - do not edit.\n")
        fo.write(" * note byte 1..96 = C-1..B-8 (0 = empty); index tables with note-1.\n")
        fo.write(" * entries 96..138 extend the range for the WAV triangle (+43).\n")
        fo.write(" * worst playable-range error: %.2f cents at %s */\n" % worst)
        fo.write("#define NOTE_MIN 1\n#define NOTE_MAX 96\n")
        fo.write("extern const unsigned char note_clock[%d];\n" % NEXT)
        fo.write("extern const unsigned char note_bkup[%d];\n" % NEXT)
        fo.write("extern const char note_names[96][3];\n")
        fo.write("extern const unsigned char wave_clock[96];\n")
        fo.write("extern const unsigned char wave_bkup[96];\n")
        fo.write("extern const unsigned char wave_step[96];\n")
    cf = open(out.replace(".h", ".c"), "w")
    cf.write("/* Generated by tools/maketables.py - do not edit. */\n")
    cf.write("const unsigned char note_clock[%d] = {\n" % NEXT)
    for i in range(0, NEXT, 12):
        cf.write("    " + ",".join("%d" % r[1] for r in rows[i:i+12]) + ",\n")
    cf.write("};\n")
    cf.write("const unsigned char note_bkup[%d] = {\n" % NEXT)
    for i in range(0, NEXT, 12):
        cf.write("    " + ",".join("%3d" % r[2] for r in rows[i:i+12]) + ",\n")
    cf.write("};\n")
    cf.write("const char note_names[96][3] = {\n")
    for i in range(0, 96, 12):
        cf.write("    " + ",".join("\"%s\"" % r[0] for r in rows[i:i+12]) + ",\n")
    cf.write("};\n")
    cf.close()
    # Wavetable playback: IRQ rate = f*32/step. Real hardware loses VBlank
    # music ticks when a ~10.5 kHz WAV shares the IRQ core with a 7.8 kHz KIT,
    # so cap WAV at ~6.25 kHz by step-doubling. Pitch stays unchanged while
    # higher notes read 16 or 8 effective table points per cycle. Use the
    # timer clock prescale for low notes so BACKUP stays 8-bit.
    fo = open(out.replace(".h", ".c"), "a")
    fo.write("/* wavetable feed: timer clock sel, BACKUP, table step */\n")
    wc, wb, ws = [], [], []
    for i in range(96):
        f = freq(i)
        step = 1
        while f * 32 / step > MAX_WAVE_IRQ and step < 8:
            step *= 2
        interval = 1e6 * step / (32 * f)      # us per IRQ
        clock = 0
        while interval / (1 << clock) > 256 and clock < 6:
            clock += 1
        b = round(interval / (1 << clock)) - 1
        b = max(0, min(255, b))
        wc.append(clock); wb.append(b); ws.append(step)
    for name, arr in (("wave_clock", wc), ("wave_bkup", wb), ("wave_step", ws)):
        fo.write("const unsigned char %s[96] = {\n" % name)
        for i in range(0, 96, 12):
            fo.write("    " + ",".join("%3d" % v for v in arr[i:i+12]) + ",\n")
        fo.write("};\n")
    fo.close()
    actual_wave_irq = [
        1e6 / ((wb[i] + 1) * (1 << wc[i])) for i in range(96)
    ]
    # The 8-entry maximum phase step cannot represent the very highest notes
    # below a 6.25 kHz Nyquist limit without changing pitch.  Guard the four
    # actual demo-pad notes that motivated the hardware fix; extreme notes
    # retain pitch and may exceed the target rather than being silently
    # clamped. Indices are A3, E4, C4, and G4 (the chain's +3 pass).
    demo_wave_notes = (33, 40, 36, 43)
    demo_wave_max = max(actual_wave_irq[i] for i in demo_wave_notes)
    assert demo_wave_max < MAX_WAVE_IRQ * 1.01
    print("notes.h: 96 notes + wave tables, worst error %.2f cents (%s); "
          "demo WAV IRQ max %.1f Hz" %
          (worst[0], worst[1], demo_wave_max))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "build/notes.h")
