#!/usr/bin/env python3
"""Build the cart-streamed ALYNXDJ HELP pages from editable plain text.

Source format:
  # comment      ignored
  blank line     blank display row
  ---            page break
  @VERSION       current VERSION + BUILDID row, supplied by the build
  anything else  one display row; leading spaces kept, trailing spaces removed

The binary is intentionally independent from the HELP renderer. It starts with
an AHD1 header and a little-endian page-offset directory. Each page contains a
line count followed by tagged length-prefixed rows. Runs of two or more spaces
are packed into one control byte whose value is the run length:
  bit 7 = inverted heading (source row contains ':')
  bits 0..5 = byte length (0 is a blank row)
"""
from pathlib import Path
import sys

MAX_W = 38
MAX_ROWS = 16
MAX_PAGES = 9                 # title indicator is deliberately one digit
MAGIC = b"AHD1"
ALLOWED = set(chr(c) for c in range(32, 97))


def fail(message):
    raise SystemExit(f"makehelp: ERROR: {message}")


def parse(path):
    pages = [[]]
    for lineno, raw in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
        line = raw.rstrip()
        if line.lstrip().startswith("#"):
            continue
        if line.strip() == "---":
            pages.append([])
            continue
        pages[-1].append((lineno, line))

    result = []
    for page in pages:
        while page and not page[0][1]:
            page.pop(0)
        while page and not page[-1][1]:
            page.pop()
        if page:
            result.append(page)
    if not result:
        fail("no pages found")
    if len(result) > MAX_PAGES:
        fail(f"{len(result)} pages > {MAX_PAGES}")
    return result


def pack_line(encoded):
    packed = bytearray()
    i = 0
    while i < len(encoded):
        if encoded[i] == 0x20:
            end = i + 1
            while end < len(encoded) and encoded[end] == 0x20:
                end += 1
            run = end - i
            while run >= 2:
                n = min(run, 31)
                packed.append(n)
                run -= n
            if run:
                packed.append(0x20)
            i = end
        else:
            packed.append(encoded[i])
            i += 1
    return packed


def encode(pages, version, buildid):
    header_len = 6 + len(pages) * 2
    data = bytearray(MAGIC + bytes((len(pages), 0)))
    data.extend(b"\0" * (len(pages) * 2))

    for page_index, page in enumerate(pages):
        if len(page) > MAX_ROWS:
            fail(f"page {page_index + 1}: {len(page)} rows > {MAX_ROWS}")
        offset = len(data)
        data[6 + page_index * 2:8 + page_index * 2] = offset.to_bytes(2, "little")
        data.append(len(page))
        for lineno, line in page:
            if line == "@VERSION":
                line = f"{version} {buildid}"
            bad = sorted(set(line) - ALLOWED)
            if bad:
                fail(f"line {lineno}: unsupported glyph(s) {bad!r}")
            if any("a" <= ch <= "z" for ch in line):
                fail(f"line {lineno}: lowercase display text is not allowed")
            encoded = line.encode("ascii")
            if len(encoded) > MAX_W:
                fail(f"line {lineno}: {len(encoded)} chars > {MAX_W}: {line!r}")
            encoded = pack_line(encoded)
            if len(encoded) > 0x3F:
                fail(f"line {lineno}: packed length exceeds 63 bytes")
            tag = len(encoded) | (0x80 if ":" in line else 0)
            data.append(tag)
            data.extend(encoded)
    assert len(data) >= header_len
    return bytes(data)


def write_header(path, page_count, data_size):
    Path(path).write_text(
        "/* Generated by tools/makehelp.py - do not edit. */\n"
        f"#define HELP_PAGES {page_count}\n"
        f"#define HELP_DATA_SIZE {data_size}\n",
        encoding="ascii",
    )


def main(argv):
    if len(argv) != 6:
        fail("usage: makehelp.py help.txt build/help.h build/help.bin VERSION BUILDID")
    pages = parse(argv[1])
    data = encode(pages, argv[4].upper(), argv[5].upper())
    if len(data) > 3 * 1024:
        fail(f"{len(data)} bytes > 3072-byte HELP data reservation")
    Path(argv[2]).parent.mkdir(parents=True, exist_ok=True)
    write_header(argv[2], len(pages), len(data))
    Path(argv[3]).write_bytes(data)
    print(f"makehelp: {len(pages)} pages, {sum(len(p) for p in pages)} rows, "
          f"{len(data)} bytes")


if __name__ == "__main__":
    main(sys.argv)
