#!/usr/bin/env python3
"""Convert art/aldj.png -> build/logo.h: a 1-bit logo bitmap.

The source is 1-bit (black ink on white). We downscale to fit the 160-wide
screen and pack the ink to 1 bit/pixel (MSB = leftmost), row-padded to a
byte. The splash expands each set bit to pen PEN_ACCENT in the framebuffer,
so the logo follows the selected UI palette. 1-bit keeps it small enough
for the tight MAIN RAM (a 4bpp copy would be ~4x bigger).
"""
import sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "art/aldj.png"
OUT = sys.argv[2] if len(sys.argv) > 2 else "build/logo.h"
TW = int(sys.argv[3]) if len(sys.argv) > 3 else 144   # target width

im = Image.open(SRC).convert("L")
if TW % 8:                       # byte-align the width for a clean blit
    TW += 8 - (TW % 8)
th = round(im.height * TW / im.width)
im = im.resize((TW, th), Image.LANCZOS)
px = im.load()

rows = []
for y in range(th):
    row = []
    for xb in range(0, TW, 8):
        b = 0
        for i in range(8):
            if px[xb + i, y] < 128:      # ink = dark -> set bit
                b |= 0x80 >> i
        row.append(b)
    rows.append(row)

with open(OUT, "w") as f:
    f.write("/* Generated by tools/makelogo.py - do not edit. */\n")
    f.write("#define LOGO_W %d\n#define LOGO_H %d\n" % (TW, th))
    f.write("static const unsigned char logo_bits[LOGO_H][LOGO_W/8] = {\n")
    for row in rows:
        f.write("    {%s},\n" % ",".join("0x%02X" % b for b in row))
    f.write("};\n")

prev = Image.new("L", (TW, th))
prev.putdata([255 if px[x, y] < 128 else 0 for y in range(th) for x in range(TW)])
prev.save("build/logo_preview.png")
print("logo %dx%d -> %s (%d bytes)" % (TW, th, OUT, th * (TW // 8)))
